### ISSUE TITLE
Linux aarch64/arm64 whl releases

### ISSUE THREAD

**Issue by kpark-hrp** [maxmind/MaxMind-DB-Reader-python#159]
Another whl release request, but I think the release action can be tweaked a little more to also support linux-aarch64.

Here is the [example](https://github.com/pypa/cibuildwheel/blob/070e744d267952ab3b86ed434d5796b707e497af/examples/github-with-qemu.yml#L17-L28):
```yml
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
```
